# Generated by Django 3.2.7 on 2021-10-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(max_length=255, unique=True, verbose_name='адрес'),
        ),
    ]
