# Generated by Django 3.2.7 on 2021-10-11 10:25

from django.db import migrations


def calculate_order_value(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    order_items_set = OrderItem.objects.all()
    for order_item in order_items_set.iterator():
        order_item.value = order_item.quantity * order_item.product.price
        order_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_orderitem_value'),
    ]

    operations = [
        migrations.RunPython(calculate_order_value)
    ]


