# Generated by Django 3.2.7 on 2021-10-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_auto_20211011_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('N', 'Необработанный'), ('C', 'Выполненный')], default='N', max_length=2),
        ),
    ]
