# Generated by Django 3.2.7 on 2021-10-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20211013_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('C', 'Наличностью'), ('E', 'Электронно')], default='C', max_length=2),
        ),
    ]
