# Generated by Django 3.2.7 on 2021-10-21 04:05

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='called',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='позвонить'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='доставлен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('C', 'Наличностью'), ('E', 'Электронно')], db_index=True, default='C', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, verbose_name='мобильный телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='registered',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='зарегистрирован'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('N', 'Необработанный'), ('C', 'Выполненный')], db_index=True, default='N', max_length=2),
        ),
    ]
