# Generated by Django 3.2.7 on 2021-10-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_alter_orderitem_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('C', 'Наличностью'), ('E', 'Электронно')], db_index=True, max_length=2, null=True),
        ),
    ]
