# Generated by Django 3.2.7 on 2021-10-21 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_alter_order_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='called',
            new_name='called_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivered',
            new_name='delivered_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='payment',
            new_name='payment_method',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='registered',
            new_name='registered_at',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='value',
            new_name='cost',
        ),
    ]
