# Generated by Django 3.2.7 on 2021-10-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_auto_20211021_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('C', 'Наличностью'), ('E', 'Электронно')], db_index=True, max_length=2, null=True),
        ),
    ]
