# Generated by Django 3.2.7 on 2021-11-03 07:15

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0055_alter_order_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='restaurant',
            managers=[
                ('restaurants', django.db.models.manager.Manager()),
            ],
        ),
    ]
